### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by fgervasi** [mitra-social/mitra-docs#10]
## Acceptance criterias
As a user, I want to log out from mitra with my registered user so that i'm leaved  the mitra world

## Notes
Any additional comments

## Tasks

- [ ] link tasks from other repositories by copying their link here

**Comment by TiMESPLiNTER** [comment]
There's no logout mechanism for backend as a JWT token can not be revoked/will be revoked automatically once the `exp` is reached.
